name: Build and Package

on:
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install MinGW
      run: |
        choco uninstall mingw -y
        choco install -y 7zip
        # Download and install MinGW 13.1.0 msvcrt
        $url = "https://github.com/niXman/mingw-builds-binaries/releases/download/13.1.0-rt_v11-rev1/x86_64-13.1.0-release-posix-seh-msvcrt-rt_v11-rev1.7z"
        $installDir = "C:\mingw64-msvcrt"
        $tempFile = "$env:TEMP\mingw-msvcrt.7z"
        Write-Host "Downloading MinGW 13.1.0 msvcrt..."
        Invoke-WebRequest -Uri $url -OutFile $tempFile
        New-Item -ItemType Directory -Path $installDir -Force
        & "C:\ProgramData\chocolatey\tools\7z.exe" x $tempFile "-o$installDir" -y
        $env:Path = ($env:Path -split ';' | Where-Object { $_ -notmatch 'C:\\mingw64\\bin' }) -join ';'
        $env:Path += ";$installDir\bin"

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.9.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        mingw: 'C:\mingw64-msvcrt'
    
    - name: Install Inno Setup
      run: |
        # Download and install Inno Setup 6
        $url = "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe"
        $output = "$env:TEMP\innosetup-6.2.2.exe"
        Write-Host "Downloading Inno Setup..."
        Invoke-WebRequest -Uri $url -OutFile $output
        
        Write-Host "Installing Inno Setup..."
        Start-Process -FilePath $output -ArgumentList "/VERYSILENT", "/NORESTART" -Wait
        
        # Verify installation
        $isccPath = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
        if (Test-Path $isccPath) {
            Write-Host "Inno Setup installed successfully at: $isccPath"
        } else {
            Write-Error "Inno Setup installation failed!"
            exit 1
        }
    
    - name: Build Windows
      env:
        Qt6_DIR: ${{ env.Qt6_DIR }}
        QT_ROOT_DIR: ${{ env.QT_ROOT_DIR }}
      run: |
        cd pack
        powershell -ExecutionPolicy Bypass -File windows.ps1
    
    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-package
        path: pack/installer/*-Setup.exe
        retention-days: 30
    
    - name: Upload Windows to Release
      if: github.event_name == 'release'
      run: |
        # Find the installer file
        $installerFile = Get-ChildItem -Path "pack/installer" -Filter "*-Setup.exe" | Select-Object -First 1
        if ($installerFile) {
          Write-Host "Uploading $($installerFile.FullName) to release..."
          gh release upload ${{ github.event.release.tag_name }} "$($installerFile.FullName)" --clobber
        } else {
          Write-Error "No installer file found!"
          exit 1
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-linux:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.9.1'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'

    - name: Build in Docker (Ubuntu 20.04, static ffmpeg)
      uses: addnab/docker-run-action@v3
      with:
        image: ubuntu:20.04
        options: >-
          -v ${{ github.workspace }}:/workspace
          -v ${{ env.Qt6_DIR }}:/qt6
        run: |
          set -e
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y tzdata build-essential git wget yasm pkg-config cmake ninja-build imagemagick fuse libfuse2

          cd /tmp
          wget https://github.com/ffmpeg/ffmpeg/archive/refs/tags/n7.1.tar.gz
          tar -xzf n7.1.tar.gz
          cd ffmpeg-7.1
          ./configure --prefix=/workspace/ffmpeg-static --enable-static --disable-shared --disable-doc --disable-programs
          make -j$(nproc)
          make install

          cd /workspace/pack
          chmod +x linux.sh
          export Qt6_DIR=/qt6
          export PKG_CONFIG_PATH=/workspace/ffmpeg-static/lib/pkgconfig:$PKG_CONFIG_PATH
          ./linux.sh

    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-package
        path: |
          pack/release/*.AppImage
          pack/deb/*.deb
        retention-days: 30
    
    - name: Upload Linux AppImage to Release
      if: github.event_name == 'release'
      run: |
        # Find the AppImage file
        appimage_file=$(find pack/release -name "*.AppImage" -type f | head -1)
        if [ -n "$appimage_file" ]; then
          echo "Uploading $appimage_file to release..."
          gh release upload ${{ github.event.release.tag_name }} "$appimage_file" --clobber
        else
          echo "No AppImage file found!"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Linux DEB to Release
      if: github.event_name == 'release'
      run: |
        # Find the DEB file
        deb_file=$(find pack/deb -name "*.deb" -type f | head -1)
        if [ -n "$deb_file" ]; then
          echo "Uploading $deb_file to release..."
          gh release upload ${{ github.event.release.tag_name }} "$deb_file" --clobber
        else
          echo "No DEB file found!"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-arm64:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.9.1'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
    
    - name: Install Dependencies
      run: |
        brew install ffmpeg@7
        brew install pkg-config
        # Set up FFmpeg environment variables for Apple Silicon
        echo "FFMPEG_DIR=/opt/homebrew/opt/ffmpeg@7" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/opt/homebrew/opt/ffmpeg@7/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
    
    - name: Build macOS ARM64
      env:
        Qt6_DIR: ${{ env.Qt6_DIR }}
        QT_ROOT_DIR: ${{ env.QT_ROOT_DIR }}
        FFMPEG_DIR: ${{ env.FFMPEG_DIR }}
        PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
      run: |
        cd pack
        chmod +x macos.sh
        ./macos.sh
    
    - name: Upload macOS ARM64 Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm64-package
        path: pack/release/*.dmg
        retention-days: 30
    
    - name: Upload macOS ARM64 to Release
      if: github.event_name == 'release'
      run: |
        # Find the DMG file
        dmg_file=$(find pack/release -name "*.dmg" -type f | head -1)
        if [ -n "$dmg_file" ]; then
          echo "Uploading $dmg_file to release..."
          gh release upload ${{ github.event.release.tag_name }} "$dmg_file" --clobber
        else
          echo "No DMG file found!"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-x86_64:
    runs-on: macos-13
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.9.1'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
    
    - name: Install Dependencies
      run: |
        brew install ffmpeg@7
        brew install pkg-config
        # Set up FFmpeg environment variables for Intel Mac
        echo "FFMPEG_DIR=/usr/local/opt/ffmpeg@7" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/usr/local/opt/ffmpeg@7/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
    
    - name: Build macOS x86_64
      env:
        Qt6_DIR: ${{ env.Qt6_DIR }}
        QT_ROOT_DIR: ${{ env.QT_ROOT_DIR }}
        FFMPEG_DIR: ${{ env.FFMPEG_DIR }}
        PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
      run: |
        cd pack
        chmod +x macos.sh
        ./macos.sh
    
    - name: Upload macOS x86_64 Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-x86_64-package
        path: pack/release/*.dmg
        retention-days: 30
    
    - name: Upload macOS x86_64 to Release
      if: github.event_name == 'release'
      run: |
        # Find the DMG file
        dmg_file=$(find pack/release -name "*.dmg" -type f | head -1)
        if [ -n "$dmg_file" ]; then
          echo "Uploading $dmg_file to release..."
          gh release upload ${{ github.event.release.tag_name }} "$dmg_file" --clobber
        else
          echo "No DMG file found!"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    needs: [build-windows, build-linux, build-macos-arm64, build-macos-x86_64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'release'
    steps:
    - name: Verify Release Assets
      run: |
        echo "All build jobs completed successfully!"
        echo "Release assets should now be available in the GitHub release."
        echo "Release tag: ${{ github.event.release.tag_name }}"
        echo "Release URL: ${{ github.event.release.html_url }}"